apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: <issuer_name>
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <your_email>
    privateKeySecretRef:
      name: <privatekey name>
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token